apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: SelfTest

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  build:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com' || cloudbees.api.url == 'https://api.cloudbees.io'
    permissions:
      scm-token-own: read
      scm-token-org: read
      id-token: write
    steps:
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Self Test
        uses: docker://golang:1.26.1
        run: |
          make verify

      - id: build-image
        name: Build, scan and push to ECR
        uses: calculi-corp/cb-internal-shared-actions/build/action@v8
        with:
          go-binary-build: "true"
          go-binary-name: configure-aws-credentials
          kaniko-build: "true"
          run-unit-test: "false"
          registry-url: 020229604682.dkr.ecr.us-east-1.amazonaws.com
          registry-image-name: actions/configure-aws-credentials
          registry-type: ECR
          oidc-iam-role: ${{ vars.oidc_staging_iam_role }}

  test-with-keys:
    #name: Check the action running on CBA using explicit keys
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    steps:
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1
      - name: Compat aws
        id: login
        uses: ./.cloudbees/testing
        with:
          aws-region: ${{ vars.cloudbees_saas_test_region }}
          aws-access-key-id: ${{ vars.cloudbees_saas_test_access_key_id }}
          aws-secret-access-key: ${{ secrets.cloudbees_saas_test_secret_access_key }}
          role-to-assume: ${{ vars.cloudbees_saas_test_role_name }}
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max
      - name: Check Output
        uses: docker://amazon/aws-cli:2.27.38
        run: |
          echo "AWS Account ID: ${{ steps.login.outputs.aws-account-id }}"
          echo "AWS Config Dir:"
          ls -l $HOME/.aws
      - name: Check auth
        uses: docker://amazon/aws-cli:2.27.38
        run: |
          aws sts get-caller-identity

  test-with-chaining:
    #name: Check authentication chaining
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    steps:
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Setup
        uses: ./.cloudbees/testing
        with:
          aws-region: ${{ vars.cloudbees_saas_test_region }}
          aws-access-key-id: ${{ vars.cloudbees_saas_test_access_key_id }}
          aws-secret-access-key: ${{ secrets.cloudbees_saas_test_secret_access_key }}

      - name: Chain
        uses: ./.cloudbees/testing
        with:
          aws-region: ${{ vars.cloudbees_saas_test_region }}
          role-chaining: "true"
          role-to-assume: ${{ vars.cloudbees_saas_test_role_name }}
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max

      - name: Check auth
        uses: docker://amazon/aws-cli:2.27.38
        run: |
          aws sts get-caller-identity

  test-with-oidc:
    #name: Check the action running on CBA using OIDC
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs:
      - build
    permissions:
      scm-token-own: read
      id-token: write
    steps:
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Compat aws
        id: login
        uses: ./.cloudbees/testing
        with:
          aws-region: ${{ vars.cloudbees_saas_test_region }}
          role-to-assume: ${{ vars.cloudbees_saas_test_role_arn }}
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max

      - name: Check Output
        uses: docker://amazon/aws-cli:2.27.38
        run: |
          echo "AWS Account ID: ${{ steps.login.outputs.aws-account-id }}"
          echo "AWS Config Dir:"
          ls -l $HOME/.aws

      - name: Check auth
        uses: docker://amazon/aws-cli:2.27.38
        run: |
          aws sts get-caller-identity
