apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: SelfTest

on:
  push:
    branches:
      - "*"

jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Self Test
        uses: docker://golang:1.21.7
        run: |
          make format sync check-git-status test
      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v0
        with:
          registry: ${{ vars.STAGING_DOCKER_REGISTRY }}
          username: ${{ secrets.STAGING_DOCKER_USERNAME }}
          password: ${{ secrets.STAGING_DOCKER_PASSWORD }}
      - name: Build and publish
        uses: cloudbees-io/kaniko
        with:
          destination: registry.saas-dev.beescloud.com/staging/configure-aws-credentials:${{ cloudbees.scm.sha }}
          labels: maintainer=sdp-pod-3,email=engineering@cloudbees.com
  compat-check:
    needs:
      - build
    #name: Check the action running on CBA
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Compat aws
        id: login
        uses: ./.cloudbees/staging
        with:
          aws-region: ${{ vars.cloudbees_saas_test_region }}
          aws-access-key-id: ${{ vars.cloudbees_saas_test_access_key_id }}
          aws-secret-access-key: ${{ secrets.cloudbees_saas_test_secret_access_key }}
          role-to-assume: ${{ vars.cloudbees_saas_test_role_name }}
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max
      - name: Check Output
        uses: docker://amazon/aws-cli:2.12.6
        run: |
          echo "AWS Account ID: ${{ steps.login.outputs.aws-account-id }}"
          echo "AWS Config Dir:"
          ls -l $HOME/.aws
      - name: Check auth
        uses: docker://amazon/aws-cli:2.12.6
        run: |
          aws sts get-caller-identity
  alt-check:
    #name: Check the action running on CBA
    needs:
      - build
    env:
      RUNNER_DEBUG: "1"
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Setup
        uses: ./.cloudbees/staging
        with:
          aws-region: ${{ vars.cloudbees_saas_test_region }}
          aws-access-key-id: ${{ vars.cloudbees_saas_test_access_key_id }}
          aws-secret-access-key: ${{ secrets.cloudbees_saas_test_secret_access_key }}
      - name: Chain
        uses: cloudbees-io/configure-aws-credentials@v0
        with:
          aws-region: ${{ vars.cloudbees_saas_test_region }}
          role-chaining: "true"
          role-to-assume: ${{ vars.cloudbees_saas_test_role_name }}
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max
      - name: Check auth
        uses: docker://amazon/aws-cli:2.12.6
        run: |
          aws sts get-caller-identity
  oidc-check:
    needs:
      - build
    permissions:
      scm-token-own: read
      id-token: write
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Compat aws
        id: login
        uses: ./.cloudbees/staging
        with:
          aws-region: ${{ vars.cloudbees_saas_test_region }}
          role-to-assume: ${{ vars.cloudbees_saas_test_role_arn }}
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max
      - name: Check Output
        uses: docker://amazon/aws-cli:2.12.6
        run: |
          echo "AWS Account ID: ${{ steps.login.outputs.aws-account-id }}"
          echo "AWS Config Dir:"
          ls -l $HOME/.aws
      - name: Check auth
        uses: docker://amazon/aws-cli:2.12.6
        run: |
          aws sts get-caller-identity
